### ISSUE TITLE
Toolbar position are wrong 

### ISSUE THREAD

**Issue by snailjj** [TimOliver/TOCropViewController#223] opened 2017-12-09 06:59 UTC
> **Please help me .**
>
> My iPhone 6s in iOS 10.3.3 ,and when a take a picture in carame,will be the picture's issue.
>

![img_0156](https://user-images.githubusercontent.com/4714351/33793350-7a177e2e-dcf1-11e7-9d04-4cccafe21ea0.PNG)

**Comment by TimOliver** [comment] 2017-12-09 09:31
Oh dear! That looks like a regression caused by the status bar work I did for iPhone X.

I just pushed a fix to `master`. Please let me know if it's working for you now!

**Comment by TimOliver** [comment] 2017-12-09 09:59
Yay! Uh, push a new version to where? CocoaPods?

**Comment by snailjj** [comment] 2017-12-09 10:00
I use cocoaPods ,thank u very much.thanks

**Comment by TimOliver** [comment] 2017-12-10 04:43
Aha! Just checking. :)

Done! I pushed a new CocoaPods version last night. Enjoy! :)

**Closed by TimOliver** 2017-12-10 04:43 UTC
Labels: bug, rfc

**Comment by snailjj** [comment] 2017-12-11 02:05
Thank u
