### ISSUE TITLE
Question: How to set immutable square crop

### ISSUE THREAD

**Issue by boyfox** [TimOliver/TOCropViewController#159] opened 2017-04-08 17:27 UTC
Hi, firstly thank you for great useful library!

I have following question, How to set immutable square crop size 1080x1080, and need disable all accessing changing crop size, I need a size of 1080 x 1080, and I need to make sure that the user could not change crop size.

Can I do like that with this library?

**Comment by TimOliver** [comment] 2017-04-10 20:37
Thanks for the question @boyfox! This sounds like a duplicate of https://github.com/TimOliver/TOCropViewController/issues/68.

At the moment, the controller doesn't publicly deal with exact pixel values; it works with aspect ratios, and determines pixel sizes based on the size of the final crop box frame against the original image's size.

I'm usually recommending that at the moment, you just set the aspect ratio to the size you want (eg 1:1 for squares) and then downscale or upscale the resulting crop image on completion.

I don't have the time to add additional features to this library at the moment, but feel free to explore the code and see if you can come up with a way to implement it. :)

I'm going to close this as it seems like a duplicate. If you think this request is actually different from #68 (Or #46), feel free to re-open. :)

Thanks!

**Closed by TimOliver** 2017-04-10 20:37 UTC
