### ISSUE TITLE
A crash on iOS 9.3.5，iPad mini

### ISSUE THREAD

**Issue by yvanda** [TimOliver/TOCropViewController#298] opened 2018-08-17 10:05 UTC
<img width="353" alt="2018-08-17 pm6 03 39" src="https://user-images.githubusercontent.com/3233066/44260779-16e12900-a248-11e8-8d53-442e7bb43ad1.png">

**Comment by yvanda** [comment] 2018-08-18 03:30
I‘m sorry，i can't post the image，but i want to know if it was caused by image with empty or size zero？

**Comment by TimOliver** [comment] 2018-08-18 04:03
I think sometimes it can be both. Although there are also times that if the math fails, the CALayer size can become zero on its own, even if the image was fine.

If you can't post the image, can you please set an exception breakpoint (https://stackoverflow.com/questions/17802662/exception-breakpoint-in-xcode) and tell me exactly the line of code causing this to fail? Thanks!

**Comment by TimOliver** [comment] 2018-08-25 23:35
There's nothing I can do without a way to reproduce this, so I'm closing it off.

If the issue is still persisting, please open a new issue with specific reproduction steps I can follow. :)

**Closed by TimOliver** 2018-08-25 23:35 UTC
Labels: bug
