### ISSUE TITLE
Problem in bypassing the default editor after selection of image from gallery/camera

### ISSUE THREAD

**Issue by vinayakpal** [TimOliver/TOCropViewController#199] opened 2017-09-19 06:30 UTC
Hi Oliver,
TOCropVC is one of the best image editor i found on internet till now. As i've a little concern is that the whenever i tried to select the image from gallery/camera it lead me to firstly went to default image editor then it gives me choice to choose or cancel. i need to directly access the TOCropVC after selection of image

**Comment by TimOliver** [comment] 2017-09-19 07:01
Thanks @vinayakpal! Glad you like it!

How exactly do you mean 'directly access'? What is your use-case exactly?

**Comment by TimOliver** [comment] 2017-09-19 07:10
Hang on. This is a duplicate of #192 isn't it? XD

I'll close this issue off here. Please follow up in that one.

**Closed by TimOliver** 2017-09-19 07:10 UTC
Labels: question, rfc
