### ISSUE TITLE
Is there a way to set the max crop height and width but still be able to make it smaller?

### ISSUE THREAD

**Issue by farhansyed9** [TimOliver/TOCropViewController#103] opened 2016-06-20 03:23 UTC

**Comment by TimOliver** [comment] 2016-06-20 18:10
No. Not at present. Sorry.

This seems like it's basically a duplicate of #46. Feel free to go in there and explain exactly what your use case is and how you'd expect this feature to work in the code. :)

**Closed by TimOliver** 2016-06-20 18:10 UTC
