### ISSUE TITLE
CropViewController.swift need to be updated for Swift 4.2

### ISSUE THREAD

**Issue by ethanwa** [TimOliver/TOCropViewController#301] opened 2018-09-13 04:37 UTC
Apologies for the vague issue earlier. 

**Change line 276:**

`public var excludedActivityTypes: [UIActivity.ActivityType]? {`

to

`public var excludedActivityTypes: [UIActivityType]? {`

**Change line 379:**

`open override var childForStatusBarStyle: UIViewController?`

to

`open override var childViewControllerForStatusBarStyle: UIViewController? {`

**Change line 387:**

`open override var childForStatusBarHidden: UIViewController? {`

to

`open override var childViewControllerForStatusBarHidden: UIViewController? {`

**Change line 445:**

```
override open var preferredScreenEdgesDeferringSystemGestures: UIRectEdge {
        if #available(iOS 11.0, *) {
            return toCropViewController.preferredScreenEdgesDeferringSystemGestures
        }
        
        return UIRectEdge.all
    }
```

to

```
override open func preferredScreenEdgesDeferringSystemGestures() -> UIRectEdge {
        if #available(iOS 11.0, *) {
            return toCropViewController.preferredScreenEdgesDeferringSystemGestures()
        }
        
        return UIRectEdge.all
    }
```

**Change line 549:**

```
extension CropViewController {
    fileprivate func setUpCropController() {
        addChild(toCropViewController)
        transitioningDelegate = (toCropViewController as! UIViewControllerTransitioningDelegate)
        toCropViewController.delegate = self
        toCropViewController.didMove(toParent: self)
    }
```

to

```
extension CropViewController {
    fileprivate func setUpCropController() {
        addChildViewController(toCropViewController)
        transitioningDelegate = (toCropViewController as! UIViewControllerTransitioningDelegate)
        toCropViewController.delegate = self
        toCropViewController.didMove(toParentViewController: self)
    }
```

**Comment by jaltreuter** [comment] 2018-09-18 22:19
Is there an estimate of when you'll release a Cocoapod update with these changes?

**Comment by grehce** [comment] 2018-11-27 00:16
**Compiler Issues:**
For line 276, 'UIActivityType' was obsoleted in Swift 4.2. 
For line 445, the Method does not override any method from its superclass.
For line 447, Expression type 'UIRectEdge' is ambiguous without more context CropViewController.swift.

Header 'CropViewController-Swift.h' not found and could not build Objective-C module 'CropViewController'

**Comment by alexeybolv** [comment] 2018-11-27 13:34
Hey, guys! Please, finish updating to swift 4,2. Thank you!

**Comment by TimOliver** [comment] 2018-11-27 13:58
Wait. I’m confused now. Has more stuff changed? The code in `master` is supposed to be up-to-date with Swift 4.2. What’s remaining exactly?

**Comment by alexeybolv** [comment] 2018-11-27 17:38
I have 2.3.8 version, but have warning to convert project to swift 4.2:
<img width="734" alt="2018-11-27 20 34 15" src="https://user-images.githubusercontent.com/14241858/49099966-de5bdd00-f283-11e8-83a8-4fa2d03c30db.png">

When I convert it automatically, it shows 7 points to me:
<img width="1395" alt="2018-11-27 20 38 06" src="https://user-images.githubusercontent.com/14241858/49100183-5f1ad900-f284-11e8-8351-c970f74b6bd4.png">

You can try to do it by yourself.

**Comment by TimOliver** [comment] 2018-11-28 02:57
I literally don't have any time to maintain this library right now. That's why I was asking people here to confirm it for me. 

That looks like you're using the CocoaPods version. Can you please pull the `master` branch version and see if those errors are still there?

**Comment by TimOliver** [comment] 2018-12-01 11:44
So I just did a 2 hour Twitch stream to update the library. :D https://www.twitch.tv/videos/343061805

I've definitely confirmed all of the Swift 4.2 issues are resolved in Xcode 10 now. I've pushed v2.4.0 on CocoaPods that includes these changes.

If there are any other issues with Swift 4.2, please open a new issue! Thanks!

**Closed by TimOliver** 2018-12-01 11:44 UTC
