### ISSUE TITLE
Status Bar Overlays Top Corners (Crop Edges) - Tall Images

### ISSUE THREAD

**Issue by juandavidcruzs** [TimOliver/TOCropViewController#220] opened 2017-11-26 17:10 UTC
- [X] I have read this issue template and provided all possible information. 
- [X] I'm using CocoaPods and have run `pod update` before filing this issue.

## Hardware / Software

Which version of the library were you using?

• Using CropViewController (2.3.4)

Which version of iOS are you running?

• iOS 11.1.2 (15B202)

What model of iOS device were you testing on?

• iPhone 7 32GB Black (A1778)

If using CocoaPods, which version of CocoaPods are you on?

• Version 1.3.1

## Goals

What is the outcome result you want to achieve with this library?

Crop an image in order to be sent to a Image Recognition Server

## Expected Results

What did you expect to happen?

Be able to drag the top corners to crop the image from there.

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

Top Corners and edge are located below the iOS Status Bar once the image is first loaded.. Making them impossible (or really difficult) to drag.  (I suppose it happens because of the height of the photo. Although it is the default Camera Size given by my AVCapturePhotoOutput)

![img_1114](https://user-images.githubusercontent.com/10634238/33242390-47e608c0-d2a2-11e7-848e-5968314e5d3d.PNG)

## Steps to Reproduce

1. Take a picture using AVCapturePhotoOutput.
2. Send the image to the CropViewController
3. Bugged Corners.

**Comment by TimOliver** [comment] 2017-11-27 04:56
Thanks for the detailed bug report @juandavidcruzs!

Something's definitely broken here. When the status bar is black, it's only kept around long enough for the presentation animation to complete, and then it's supposed to fade out afterwards (This is so other elements like underlying `UINavigationController` don't play any status bar related animations during the transition). 

The fact that it's still visible here isn't right. As far as I can tell, the crop box is behaving correctly (It's assuming the status bar is hidden), so it would imply something broken with the way the crop controller was being presented on screen. It's probably something I've missed with `CropViewController` delegating its status bar logic to the internal `TOCropViewController`.

Can you please post the code you've written that instantiates `CropViewController` and then presents it onscreen? I'll see if I can reproduce it in the sample app.

Thanks!

**Comment by TimOliver** [comment] 2017-12-14 06:27
Closing this issue since it hasn't been followed up in over 2 weeks. 

If the problem is still persisting, please open a new issue and provide sample code on how the view controller is being presented, and what sort of view controller hierarchy your app has.

Thanks! :)

**Closed by TimOliver** 2017-12-14 06:27 UTC
Labels: bug
