### ISSUE TITLE
Quickly click any tool bar buttons(while processing large image) and the blocks will invoke many times.

### ISSUE THREAD

**Issue by swulog** [TimOliver/TOCropViewController#454] opened 2020-12-12 05:22 UTC
**Describe the bug**
After edited a large(more than 5M) image. I quickly clicked the done button more than ONE times.
And I found that delegate method [cropViewController:didCropToImage:withRect:angle] have been called many times.

**To Reproduce**
See the description

**Expected behavior**
Fix it.

**Screenshots**
None

**iOS Device:**
 - Device: [iPhone XS]
 - OS: [iOS 14.2]
 - Library Version [2.5.5]

**Additional context**
None

**Comment by TimOliver** [comment] 2020-12-12 05:47
Sorry @swulog. There's not enough information here to know what is going on. Please go back and fill out the issue template to explain exactly what the problem is and how it should be fixed.

Thanks!

**Comment by TimOliver** [comment] 2020-12-31 03:31
Closing this off due to inactivity. If this issue is still causing you problems, please open a new issue and fill out the issue template with as much info as you can. :)

Thanks!

**Closed** 2020-12-31 04:13 UTC
Labels: bug
