### ISSUE TITLE
cropImage to center for TOCropViewControllerAspectRatioPreset4x3

### ISSUE THREAD

**Issue by rakeshkathoju** [TimOliver/TOCropViewController#243] opened 2018-01-31 10:11 UTC
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

---
> Hi Tim, when i am trying to crop image with aspectratio 4X3 , the image is cropping from top(Leaving more image at bottom), i want it to crop all sides equally. like in TOCropViewControllerAspectRatioPresetSquare , please help me,Thanks in advance .

---

## Hardware / Software

Which version of the library were you using?
Which version of iOS are you running? 
What model of iOS device were you testing on?
If using CocoaPods, which version of CocoaPods are you on?

## Goals
This is the outcome result i want to achieve with this library?
![simulator screen shot - iphone 8 plus - 2018-01-31 at 15 47 17](https://user-images.githubusercontent.com/23329327/35617508-655503ae-069e-11e8-8dfe-15bd93f5f2a8.png)

## Expected Results
![simulator screen shot - iphone 8 plus - 2018-01-31 at 15 47 17](https://user-images.githubusercontent.com/23329327/35617453-466e64e4-069e-11e8-95f5-12f88fe8059f.png)

What did you expect to happen?

## Actual Results
![simulator screen shot - iphone 8 plus - 2018-01-31 at 15 46 38](https://user-images.githubusercontent.com/23329327/35617475-50bd7430-069e-11e8-8803-799c1e7a5456.png)

What happened instead?  (Please attach a screenshot/screen recording if possible)

## select any portrait photo set aspect ratio to 4X3, you will see 
![simulator screen shot - iphone 8 plus - 2018-01-31 at 15 46 59](https://user-images.githubusercontent.com/23329327/35617399-162cec88-069e-11e8-985f-7e2e167f8958.png)
![simulator screen shot - iphone 8 plus - 2018-01-31 at 15 46 38](https://user-images.githubusercontent.com/23329327/35617402-18253806-069e-11e8-9e10-e84abcaf50e1.png)

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

**Comment by TimOliver** [comment] 2018-02-01 05:13
Thanks for the issue @rakeshkathoju!

Ah yeah, I've seen this issue manifest. It seems to happen depending on the size of the image, but I haven't found a pattern in it. It's not an absolute showstopper, so I haven't dedicated too much time to it.

If anyone else would like to work out what would be causing this, the offending code is in here: https://github.com/TimOliver/TOCropViewController/blob/master/Objective-C/TOCropViewController/Views/TOCropView.m#L1336

A PR would be very warmly welcomed. :D

**Comment by TimOliver** [comment] 2018-08-14 16:03
I decided to have a very quick look at this now. I think I found the cause.

Please pull from `master` and see if that's fixed it. :)

**Comment by TimOliver** [comment] 2018-08-20 14:18
Gonna close this off since I'm 99% it's fixed.

Please feel free to re-open if not. :)

**Closed by TimOliver** 2018-08-20 14:18 UTC
Labels: bug, rfc
