### ISSUE TITLE
Image Zoomed In with Circular Crop

### ISSUE THREAD

**Issue by inPhilly** [TimOliver/TOCropViewController#203] opened 2017-10-05 21:42 UTC
- [x] I have read this issue template and provided all possible information. 
- [ ] I'm using CocoaPods and have run `pod update` before filing this issue.

---
> **Please remove this section of the issue template before filing your issue.**
>
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> Please note that your issue may be closed without review if you do not supply 
> the information that is requested here. Since this library is done as a side-project 
> outside of work hours, please understand that a timely response cannot be guaranteed. ;)
>
> ## For CocoaPods Users
>
> Before filing a bug report, please make sure you are using the latest version
> of CocoaPods (`gem install cocoapods`), and the latest version of this 
> library (`pod repo update`).
>
> Support for CocoaPods-related issues is not provided unless you confirm both of 
> these points in your submission.
>
> ## Issue Types
> 
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describe the bug you've discovered. If it's 
> a visual bug, please add a screenshot. If it's an animation bug, please provide a recording 
> of the bug in action.
>
>
---

## Hardware / Software

Which version of the library were you using?
Which version of iOS are you running?
What model of iOS device were you testing on?
If using CocoaPods, which version of CocoaPods are you on?

## Goals

What is the outcome result you want to achieve with this library?

## Expected Results

What did you expect to happen?

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

**Comment by inPhilly** [comment] 2017-10-05 21:49
Sorry, I'm having issues tonight. My issue is that, when using the Circular crop option, the image is VERY zoomed in and mostly unrecognizable. I did look in the comments and couldn't find the same issue. I am testing on an iOS simulator for iPad Pro 10.5 inch, iOS 10.3, using the images in the simulator. I am using imagePicker first and then pushing this controller with the selected image. The method you use in your example is deprecated:

`- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingImage:(UIImage *)image editingInfo:(NSDictionary *)editingInfo`

 so I use:

```
- (void)imagePickerController:(UIImagePickerController *)imagePicker didFinishPickingMediaWithInfo:(NSDictionary *)info {
    self.originalImageFromPicker = [info objectForKey:UIImagePickerControllerOriginalImage];
    TOCropViewController *cropController = [[TOCropViewController alloc] initWithCroppingStyle:TOCropViewCroppingStyleCircular image:self.originalImageFromPicker];
    cropController.delegate = self;
    [imagePicker pushViewController:cropController animated:YES];
}
```

**Comment by inPhilly** [comment] 2017-10-05 21:58
I know it's crazy but I can't figure out where to find the library version - I pulled it down via Carthage just yesterday, and I didn't specify a version.

**Comment by inPhilly** [comment] 2017-10-05 22:00
I did find a similar issue - pretty much the issue I am having - but this issue is closed unfortunately:
https://github.com/TimOliver/TOCropViewController/issues/198

**Comment by inPhilly** [comment] 2017-10-05 22:03
I checked in the terminal and the latest version of Carthage pulls down the 2.1.0 version of TOCropImageViewController.

**Comment by TimOliver** [comment] 2017-10-11 05:34
Hi @inPhilly! Some screenshots and reproduction steps would help a lot! :D

**Comment by inPhilly** [comment] 2017-10-24 19:41
Hi Tim. I tried to include my reproduction steps with the below code. What else can I show you that would help? I will add a screenshot  - it is pretty much exactly the same thing that is happening in issue 198 referenced above. Thanks.

```
- (void)imagePickerController:(UIImagePickerController *)imagePicker didFinishPickingMediaWithInfo:(NSDictionary *)info {
    self.originalImageFromPicker = [info objectForKey:UIImagePickerControllerOriginalImage];
    TOCropViewController *cropController = [[TOCropViewController alloc] initWithCroppingStyle:TOCropViewCroppingStyleCircular image:self.originalImageFromPicker];
    cropController.delegate = self;
    [imagePicker pushViewController:cropController animated:YES];
}
```

**Comment by inPhilly** [comment] 2017-10-24 19:54
So far I have tried iPad Air 2 (10.3.1 and 11.0.1) and iPad Pro 10.5 inch (10.3.1 and 11.0.1), and they are all having the same issue.
I am using a UISplitViewController on an iPad. From one of the views within the UISplitViewController, I press en edit button to edit a Profile. The Profile View is presented modally, with a UINavigationBar, in a Form Sheet. Within the Profile View, there is a profile image button. When I press the profile image button, I present the UIImagePickerController. Once an image is picked, this method is called:

```
- (void)imagePickerController:(UIImagePickerController *)imagePicker didFinishPickingMediaWithInfo:(NSDictionary *)info {
    self.originalImageFromPicker = [info objectForKey:UIImagePickerControllerOriginalImage];
    TOCropViewController *cropController = [[TOCropViewController alloc] initWithCroppingStyle:TOCropViewCroppingStyleCircular image:self.originalImageFromPicker];
    cropController.delegate = self;
    [imagePicker pushViewController:cropController animated:YES];
}
```

**Comment by inPhilly** [comment] 2017-10-24 20:08
Here is a screenshot of the zooming that is happening:
<img width="492" alt="screen shot 2017-10-24 at 4 07 00 pm" src="https://user-images.githubusercontent.com/1884802/31965476-86b26e68-b8d5-11e7-8a5d-94ede0fee60a.png">

**Comment by inPhilly** [comment] 2017-10-24 20:10
Whereas this is how the same photo looks on iPhone 8.

<img width="408" alt="screen shot 2017-10-24 at 4 09 48 pm" src="https://user-images.githubusercontent.com/1884802/31965618-e3f67f92-b8d5-11e7-861f-56a1472df936.png">

**Comment by inPhilly** [comment] 2017-10-24 20:11
I hope this helps. Please let me know if I can provide any further information.

**Comment by rcorin** [comment] 2017-10-30 16:01
hello! I'm seeing the same issue. Any news on this?

**Comment by inPhilly** [comment] 2017-11-10 05:36
No, no news. Sorry.

**Comment by inPhilly** [comment] 2017-11-10 05:52
Hi Tim - I don't know if you will get this message.. but did you have any thoughts on this issue?

**Comment by inPhilly** [comment] 2017-11-10 07:28
So I figured out the issue - is this a bug? I get this issue when I add in the following lines of code

cropController.aspectRatioPickerButtonHidden = YES;
cropController.rotateClockwiseButtonHidden = YES;
cropController.rotateButtonsHidden = YES;

When I comment out those three lines, things seem to work, so far! I would be curious to hear your thoughts on this. Thanks!

**Comment by inPhilly** [comment] 2017-11-10 07:32
Also, I am now using the downloaded version of this controller as opposed to Carthage, as the downloaded version seems to work better with iPhone X. Thanks again for this great control.

**Comment by TimOliver** [comment] 2017-11-16 16:51
Hi folks! Sorry for the delay.

I had to shuffle a lot of the setup code in my latest version in order to make iPhone X support work properly (Since the views need to be added to the hierarchy for `safeAreaInsets` to be valid etc).

This SHOULD hopefully have solved this problem once and for all since it means the setup logic is deferred until the view is presented onscreen at its final size.

Please let me know if this is still persisting in v 2.2. Thanks!

**Comment by TimOliver** [comment] 2017-11-19 03:40
Alrighty. I'm reasonably confident I've fixed this with the changes I made iPhone X support, so I'm going to close this. Let me know if it's still persisting!

**Closed by TimOliver** 2017-11-19 03:40 UTC
Labels: rfc

**Comment by pksmile** [comment] 2020-07-16 08:39
Hi @TimOliver ,
while using circular crop image is so much zoomed but i want this has to shown in normal size or inside crop size. I am using version 2.5.3

See attached image, **ZoomedInWithBackground.png** this is how it looks by default but i need that like **ZoomedOut.png**, is there any setting or any value what i can change and use? 
![ZoomedInWithBackground](https://user-images.githubusercontent.com/16712848/87649401-fb526600-c76f-11ea-97e3-4574b03b0a00.png)
![ZoomedOut](https://user-images.githubusercontent.com/16712848/87649426-02797400-c770-11ea-969f-2074214d23f3.png)
