### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by narendra-ct** [TimOliver/TOCropViewController#277] opened 2018-05-27 18:02 UTC
Hello,

Application crash after selecting done button (cropstye default) in Xcode 9.3.1 and tried with simulator.

2018-05-27 23:30:42.389158+0530 CropViewControllerExample[32131:3049224] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIImage croppedImageWithFrame:angle:circularClip:]: unrecognized selector sent to instance 0x6000002a6a80'

thanks,
Narendra.

**Comment by LucyJeong** [comment] 2018-05-31 08:18
Hi, @narendra-ct 
I got same issue 😢This problem came from recently updated 2 commit. I fixed two line of code in UIImage+CropRotate.m

You can see below commit
https://github.com/LucyJeong/TOCropViewController/commit/6406e6bcf6e9ac37f5b6eb1c6c234587b8229928

**Comment by TimOliver** [comment] 2018-07-22 15:34
Duplicate of #268. This should hopefully be fixed at this point. :)

**Closed by TimOliver** 2018-07-22 15:34 UTC
