### ISSUE TITLE
Rotation of image without changing the frame of Crop Rect from Landscape to portrate

### ISSUE THREAD

**Issue by ritesh-kumar42** [TimOliver/TOCropViewController#156] opened 2017-03-26 17:58 UTC
## Hardware / Software

version of the library 2.0.12
Version of iOS  10
Universal

## Goals

I want to rotate image but i don't want to change the form of crop rect as of now it's changing the frame of Crop rect.

## Expected Results

Image should rotate but Crop Frame should remain same as it was before rotation. Like Crop frame is 4:3 and we are rotation image, in this case, image should rotate but frame should remain in 4:3 it should not change to 3:4.

Please help here.

**Comment by TimOliver** [comment] 2017-03-26 20:03
Thanks for the issue! But this is a duplicate of #51. It's up for grabs if you'd like to try and implement it yourself. :)

**Closed by TimOliver** 2017-03-26 20:03 UTC
