### ISSUE TITLE
GridOverlayView not proper for Portrait images 

### ISSUE THREAD

**Issue by VJM158** [TimOliver/TOCropViewController#253] opened 2018-02-22 08:33 UTC
Hi Tim,

I have updated to latest pod but seems GridOverlayView is not proper for Portrait images. In previous version this was working as expected. PFA screenshot.

Xcode: 9.2
Simulator : iPhone 7, 11.2

![simulator screen shot - iphone 7 - 2018-02-22 at 00 26 34](https://user-images.githubusercontent.com/23058004/36527741-c2a77828-1767-11e8-909f-d1efb456c34c.png)

Please suggest.

Regards
Vijay

**Comment by TimOliver** [comment] 2018-03-07 02:09
Hi @VJM158!

Hmm, can you please attach your code for presenting the controller so I can see which settings you are using? Thanks!

**Comment by VJM158** [comment] 2018-03-07 04:19
Hi Tim,

Thanks for your response. I am using below code on tap of button:

        let cropVC = TOCropViewController(image: image)
        cropVC.aspectRatioLockEnabled = false
        cropVC.rotateButtonsHidden = true
        cropVC.aspectRatioPickerButtonHidden = true
        cropVC.cropView.cropBoxResizeEnabled = false
        cropVC.aspectRatioPreset = order.printSize.cropRatio
        cropVC.delegate = self
        activeViewController?.present(cropVC, animated: true, completion: nil)

Below is the definition of ActiveViewController:

private var activeViewController: UIViewController? {
        let appDel = UIApplication.shared.delegate as? AppDelegate
        let window = appDel?.window
        let navigationController = window?.rootViewController as? UINavigationController
        return navigationController?.visibleViewController
    }

Thank You!!

Regards
Vijay

**Comment by TimOliver** [comment] 2018-08-14 15:35
Hi @VJM158. Sorry for the delay. I've updated the library a fair bit since March. Can you please confirm this is still an issue? Thanks!

**Comment by TimOliver** [comment] 2018-08-20 14:15
Gonna close this off since I "think" it's been fixed.

If it's still persisting, please open a new issue and provide detail steps for reproduction. :)

**Closed** 2018-08-20 14:16 UTC
Labels: bug, rfc
