### ISSUE TITLE
I need no matter how to rotate the picture, gridOverlayView is guaranteed for the horizontal 1:2 ratio, rather than the horizontal 1:2, rotation for the vertical into the 2:1, meaning that only the rotation of the picture, the clip box does not rotate

### ISSUE THREAD

**Issue by huangxuan518** [TimOliver/TOCropViewController#100] opened 2016-06-13 05:24 UTC
I need no matter how to rotate the picture, gridOverlayView is guaranteed for the horizontal 1:2 ratio, rather than the horizontal 1:2, rotation for the vertical into the 2:1, meaning that only the rotation of the picture, the clip box does not rotate

**Comment by TimOliver** [comment] 2016-06-14 18:00
I think this is a duplicate of https://github.com/TimOliver/TOCropViewController/issues/51. :)

**Closed by TimOliver** 2016-06-14 18:00 UTC
Labels: duplicate
