### ISSUE TITLE
Rotate wheel

### ISSUE THREAD

**Issue by debug29** [TimOliver/TOCropViewController#3] opened 2015-06-24 08:59 UTC
It would be nice to implement a rotate wheel, every time i implement crop in my app, all crop library never have rotate wheel and also it's really hard to edit it to add this possibility. 

If you could add it, your crop lib, will be the better on Github.

**Comment by TimOliver** [comment] 2015-06-24 13:46
I was considering this sort of the feature, under the name of 'fine-grain rotations'. It's something I'd love to have, but it wasn't feasible for me to add.

The problem is that introduces a new layer of complexity that I wasn't sure how to handle. If you look at the Photos app, when you rotate an image with the wheel, the crop view is smart enough to zoom the image in, so the box still stays within the bounds of the image, and when you swipe around, the box only allows scrolling in that the box still stays inside the image. There's some pretty epic math going on there.

The main problem I couldn't figure out was how you could get a scroll view to constrain its scroll bounds to a rotated image. One of my colleagues suggested it might be a simple matter of rotating the whole scroll view, but that would require some testing, and may not even work.

Anyway, the crux of the matter is that while it'd be a really cool feature to have, I don't really have a need for it in [my own use case for this library](http://icomics.co), and so it's not worth me spending the time researching, implementing and debugging this.

If anyone else thinks they know how to implement this, feel free to contribute a PR (But ONLY if it behaves like the iOS 8 Photos app). In the meantime, I'll leave this issue open.

**Comment by debug29** [comment] 2015-06-24 14:41
I will try to make it, as i said, i'm not a huge iOS developer. But why not try :smiley: . If i make it, i reply in this issue.

**Comment by kronik** [comment] 2015-06-25 05:57
Maybe [SWImageRotation](https://github.com/SurpriseWave/SWImageRotation) might help to simplify logic?

**Comment by TimOliver** [comment] 2015-06-25 06:31
Oh! Thanks for the heads-up on that library! I hadn't seen that one before.

Hrmm, I just downloaded it and had a play with it. It certainly allows fine-grain rotations, but the image isn't inside a scroll view, so you can't drag it around. That in itself is very easy to implement, but it's the first part of the puzzle for the sort of feature we're talking about here.

I'm pretty sure the solution involves actually rotating the `UIScrollView` as a whole, and adjusting the `contentSize` to match the bounds of the cropping box somehow. This is opposed to the '90-degree' feature in there already as that actually just rotates the image view, but leaves the rest of the view untouched.

It probably just needs a lot of experimentation and playing around with a `UIScrollView` to work out how it behaves when it's rotated, but that's sadly something someone else is going to have to try out.

**Comment by debug29** [comment] 2015-06-26 08:34
Thanks, i'll take a look.

2015-06-25 8:31 GMT+02:00 Tim Oliver <notifications@github.com>:

> Oh! Thanks for the heads-up on that library! I hadn't seen that one before.
>
> Hrmm, I just downloaded it and had a play with it. It certainly allows
> fine-grain rotations, but the image isn't inside a scroll view, so you
> can't drag it around. That in itself is very easy to implement, but it's
> the first part of the puzzle for the sort of feature we're talking about
> here.
>
> I'm pretty sure the solution involves actually rotating the UIScrollView
> as a whole, and adjusting the contentSize to match the bounds of the
> cropping box somehow. This is opposed to the '90-degree' feature in there
> already as that actually just rotates the image view, but leaves the rest
> of the view untouched.
>
> It probably just needs a lot of experimentation and playing around with a
> UIScrollView to work out how it behaves when it's rotated, but that's
> sadly something someone else is going to have to try out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TimOliver/TOCropViewController/issues/3#issuecomment-115123311>
> .
>



-- 
Florian COULON
Skype : fcoulon1
Tel Perso : 06.76.48.50.53
E-mail : f.m.coulon@gmail.com

**Comment by TimOliver** [comment] 2015-12-19 14:19
I'm going to close this off, since I'm probably not going to get the chance to implement it.

Like I said above, I'm pretty sure this is simply just a matter of applying a rotation to the `transform` property of the `UIScrollView`. After breaking down Apple's own cropper, I now think they actually did implement theirs in the traditional sense, where they've actually got a hole in the dimming view. This is opposed to my implementation where a clipped copy of the image is being displayed over the image view.

If this is the case, then it would mean having to basically scrap the entire implementation of this cropper view and rewriting it from scratch, sadly something I don't have time for.

If you're still interested in trying to write one yourself, I wish you all the best of luck! :)

**Closed by TimOliver** 2015-12-19 14:19 UTC
